### ISSUE TITLE
No longer possible to set spring.cloud.config.uri as environment variable

### ISSUE THREAD

**Issue by Juliet-Unsilo** [spring-projects/spring-cloud#22]
I have an example project with the following bootstrap file:
```
spring:
  application:
    name: example
  cloud:
    config:
      failFast: true

```
The spring.cloud.config.uri, which is set as an environment variable is ignored, instead the default is used: http://localhost:8888

[demo-new.zip](https://github.com/spring-projects/spring-cloud/files/1449256/demo-new.zip)

Note: The same setup works using spring.cloud version Dalston.SR4 together with spring boot version 1.5.8.release
