### ISSUE TITLE
Could not restart  when integration spring-cloud-starter-bus-amqp

### ISSUE THREAD

**Issue by koradji2046** [spring-projects/spring-cloud#39]
### POM.xml
```xml
    <packaging>jar</packaging>
    <artifactId>microservice-config-server</artifactId>
    <version>1.0-SNAPSHOT</version>
    <groupId>com.yangyang.cloud</groupId>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.10.RELEASE</version>
    </parent>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Edgware.SR3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-server</artifactId>
        </dependency>
	<dependency>
	      <groupId>org.springframework.boot</groupId>
	      <artifactId>spring-boot-starter-actuator</artifactId>
	</dependency>
	<dependency>
	      <groupId>org.springframework.cloud</groupId>
	      <artifactId>spring-cloud-starter-bus-amqp</artifactId>
	</dependency>
   </dependencies>
</project>
```
### application.yml
```
server.port: 8040
spring.application.name: microservice-config-server
spring.profiles.active: native

endpoints.shutdown.enabled: true
endpoints.restart.enabled: true
endpoints.shutdown.sensitive: false
endpoints.restart.sensitive: false

security.basic.enabled: false

management:
  security.enabled: false
  context-path: /admin
```
### App.java
```java
@SpringBootApplication
@EnableConfigServer
public class App {
    public static void main(String[] args) {
        SpringApplication.run(ConfigServerApplication.class,args);
    }
}
```

curl -x post localhost:8040/admin/restart

app.jar reported error:
`
java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext@4b86805d has been closed already
`

**Comment by spencergibb** [comment]
The correct repo to file an issue is https://github.com/spring-cloud/spring-cloud-bus

That being said, you don't have `spring-boot-starter-web`.

**Comment by koradji2046** [comment]
No, sir:
1 spring-cloud-starter-bus-amqp had referred spring-boot-starter-web

**Comment by koradji2046** [comment]
Now, the problem has reappeared, why?

**Comment by ryanjbaxter** [comment]
https://github.com/spring-projects/spring-cloud/issues/39#issuecomment-467281515

**Comment by koradji2046** [comment]
I review all pom.xml and found:

**Comment by koradji2046** [comment]
I review all pom.xml and found:

when use:
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.10.RELEASE</version>
    </parent>

    <dependencyManagement>
        <dependencies>
			<dependency>
			    <groupId>org.springframework.cloud</groupId>
			    <artifactId>spring-cloud-starter-bus-amqp</artifactId>
			    <version>1.3.4.RELEASE</version>
			</dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>

				<version>Dalston.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

the /admin/restart is OK,but use  <version>Edgware.SR6</version> then the /admin/restart is failed!

**Comment by koradji2046** [comment]
I review all pom.xml and found:

in pom.xml, when use:
-------------------------------
<parent>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-parent</artifactId>
  <version>1.5.10.RELEASE</version>
</parent>

<dependencyManagement>
    <dependencies>
	<dependency>
	    <groupId>org.springframework.cloud</groupId>
	    <artifactId>spring-cloud-starter-bus-amqp</artifactId>
	    <version>1.3.4.RELEASE</version>
	</dependency>
	<dependency>
	    <groupId>org.springframework.cloud</groupId>
	    <artifactId>spring-cloud-dependencies</artifactId>
	    <version>Dalston.RELEASE</version>
	    <type>pom</type>
	    <scope>import</scope>
	</dependency>
    </dependencies>
</dependencyManagement>
-------------------------------

the /admin/restart is OK,

but use 
-------------------------------
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-dependencies</artifactId>
    <version>Edgware.SR6</version> 
    <type>pom</type>
    <scope>import</scope>
</dependency>
-------------------------------
then the /admin/restart is failed!

**Comment by koradji2046** [comment]
I review all pom.xml and found:

in pom.xml, when use:

```
<parent>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-parent</artifactId>
  <version>1.5.10.RELEASE</version>
</parent>

<dependencyManagement>
    <dependencies>
	<dependency>
	    <groupId>org.springframework.cloud</groupId>
	    <artifactId>spring-cloud-starter-bus-amqp</artifactId>
	    <version>1.3.4.RELEASE</version>
	</dependency>
	<dependency>
	    <groupId>org.springframework.cloud</groupId>
	    <artifactId>spring-cloud-dependencies</artifactId>
	    <version>Dalston.RELEASE</version>
	    <type>pom</type>
	    <scope>import</scope>
	</dependency>
    </dependencies>
</dependencyManagement>
```
the /admin/restart is OK,

but when use:
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-dependencies</artifactId>
    <version>Edgware.SR6</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```
then the /admin/restart is failed!

**Comment by spencergibb** [comment]
/actuator/restart

**Comment by koradji2046** [comment]
i'd set:
'''
server.context-path: /admin
'''
and complete application.yml :
```
server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  profiles:
    active: native

endpoints:
  shutdown:
    enabled: true
    sensitive: false
  restart:
    enabled: true
    sensitive: false

security.basic.enabled: false
management:
  security.enabled: false
  context-path: /admin

---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations: D:/work/spring-cloud-microservice-study/config-repo
  rabbitmq:
    host: localhost
    port: 5672
    username: qzdatasoft
    password: xxxx
    virtual-host: /
```
